### ISSUE TITLE
Did not speed up anything

### ISSUE THREAD

**Issue by OneDivZero** [wavii/rails-dev-tweaks#15]
Did I miss anything? I have not a percent more speed achieved. I did some comparements and it got even slower on average (200 - 300 ms). Using the latest thin-server. Thanks!

**Comment by Lordnibbler** [comment]
@OneDivZero I had the same results on Thin 1.5.1 and rails 3.2.13

**Comment by OneDivZero** [comment]
Yes thin 1.5.1 but I'm on rails 3.2.3. Do you have an idea? I checked the docs twice, but it should work out of the box.
I searched on the web also for alternatives, but I only found references for this gem.

**Comment by garrettlancaster** [comment]
Also experiencing no speedup whatsoever, any resolution to this?

**Comment by pierre-pretorius** [comment]
It makes big difference when using JRuby since it reduces compilation time.  For normal Ruby I suspect it will slow things down until pull request https://github.com/wavii/rails-dev-tweaks/pull/9 is merged.  I did a bit of testing with and without the pull request.  No idea why it hasn't been merged yet.

**Comment by nevir** [comment]
Sorry for the huge delay but #9 is out now via `1.2`
